//! Code generated by sqlc-gen-rust. SHOULD NOT EDIT.
//! sqlc version: v1.31.1
//! sqlc-gen-rust version: v0.1.12

pub trait RusqliteClient {
    fn prepare(&self, sql: &str) -> rusqlite::Result<rusqlite::Statement<'_>>;
}
impl RusqliteClient for rusqlite::Connection {
    fn prepare(&self, sql: &str) -> rusqlite::Result<rusqlite::Statement<'_>> {
        self.prepare(sql)
    }
}
impl RusqliteClient for rusqlite::Transaction<'_> {
    fn prepare(&self, sql: &str) -> rusqlite::Result<rusqlite::Statement<'_>> {
        rusqlite::Connection::prepare(&self, sql)
    }
}
pub struct InsertOrUpdateItemRow {
    pub id: i64,
}
impl InsertOrUpdateItemRow {
    pub fn from_row(row: &rusqlite::Row) -> rusqlite::Result<Self> {
        Ok(Self { id: row.get(0)? })
    }
}
pub struct InsertOrUpdateItem<'a> {
    item: &'a str,
    base_score: i64,
    create_time: i64,
    update_time: i64,
}
impl<'a> InsertOrUpdateItem<'a> {
    pub const QUERY: &'static str = r"INSERT INTO item(item, base_score, create_time, update_time)
VALUES (?, ?, ?, ?)
ON CONFLICT (item) DO UPDATE
SET
  item = excluded.item
RETURNING id";
    pub fn query_str(&self) -> &str {
        Self::QUERY
    }
}
impl<'a> InsertOrUpdateItem<'a> {
    pub fn query_one(
        &self,
        client: &impl RusqliteClient,
    ) -> rusqlite::Result<InsertOrUpdateItemRow> {
        self.prepare(client)?
            .query_row(self.as_params(), InsertOrUpdateItemRow::from_row)
    }
    pub fn query_opt(
        &self,
        client: &impl RusqliteClient,
    ) -> rusqlite::Result<Option<InsertOrUpdateItemRow>> {
        self.prepare(client)?
            .query_map(self.as_params(), InsertOrUpdateItemRow::from_row)?
            .next()
            .transpose()
    }
    pub fn prepare<'conn>(
        &self,
        client: &'conn impl RusqliteClient,
    ) -> rusqlite::Result<rusqlite::Statement<'conn>> {
        client.prepare(self.query_str())
    }
    pub fn as_params(&self) -> impl rusqlite::Params {
        (
            self.item,
            self.base_score,
            self.create_time,
            self.update_time,
        )
    }
}
impl<'a> InsertOrUpdateItem<'a> {
    pub const fn builder() -> InsertOrUpdateItemBuilder<'a, ((), (), (), ())> {
        InsertOrUpdateItemBuilder {
            fields: ((), (), (), ()),
            _phantom: std::marker::PhantomData,
        }
    }
}
pub struct InsertOrUpdateItemBuilder<'a, Fields = ((), (), (), ())> {
    fields: Fields,
    _phantom: std::marker::PhantomData<&'a ()>,
}
impl<'a, BaseScore, CreateTime, UpdateTime>
    InsertOrUpdateItemBuilder<'a, ((), BaseScore, CreateTime, UpdateTime)>
{
    pub fn item(
        self,
        item: &'a str,
    ) -> InsertOrUpdateItemBuilder<'a, (&'a str, BaseScore, CreateTime, UpdateTime)> {
        let ((), base_score, create_time, update_time) = self.fields;
        let _phantom = self._phantom;
        InsertOrUpdateItemBuilder {
            fields: (item, base_score, create_time, update_time),
            _phantom,
        }
    }
}
impl<'a, Item, CreateTime, UpdateTime>
    InsertOrUpdateItemBuilder<'a, (Item, (), CreateTime, UpdateTime)>
{
    pub fn base_score(
        self,
        base_score: i64,
    ) -> InsertOrUpdateItemBuilder<'a, (Item, i64, CreateTime, UpdateTime)> {
        let (item, (), create_time, update_time) = self.fields;
        let _phantom = self._phantom;
        InsertOrUpdateItemBuilder {
            fields: (item, base_score, create_time, update_time),
            _phantom,
        }
    }
}
impl<'a, Item, BaseScore, UpdateTime>
    InsertOrUpdateItemBuilder<'a, (Item, BaseScore, (), UpdateTime)>
{
    pub fn create_time(
        self,
        create_time: i64,
    ) -> InsertOrUpdateItemBuilder<'a, (Item, BaseScore, i64, UpdateTime)> {
        let (item, base_score, (), update_time) = self.fields;
        let _phantom = self._phantom;
        InsertOrUpdateItemBuilder {
            fields: (item, base_score, create_time, update_time),
            _phantom,
        }
    }
}
impl<'a, Item, BaseScore, CreateTime>
    InsertOrUpdateItemBuilder<'a, (Item, BaseScore, CreateTime, ())>
{
    pub fn update_time(
        self,
        update_time: i64,
    ) -> InsertOrUpdateItemBuilder<'a, (Item, BaseScore, CreateTime, i64)> {
        let (item, base_score, create_time, ()) = self.fields;
        let _phantom = self._phantom;
        InsertOrUpdateItemBuilder {
            fields: (item, base_score, create_time, update_time),
            _phantom,
        }
    }
}
impl<'a> InsertOrUpdateItemBuilder<'a, (&'a str, i64, i64, i64)> {
    pub fn build(self) -> InsertOrUpdateItem<'a> {
        let (item, base_score, create_time, update_time) = self.fields;
        InsertOrUpdateItem {
            item,
            base_score,
            create_time,
            update_time,
        }
    }
}
pub struct InsertIntoAccessLogRow {}
impl InsertIntoAccessLogRow {
    pub fn from_row(row: &rusqlite::Row) -> rusqlite::Result<Self> {
        Ok(Self {})
    }
}
pub struct InsertIntoAccessLog {
    item_id: i64,
    access_time: i64,
}
impl InsertIntoAccessLog {
    pub const QUERY: &'static str = r"INSERT INTO access_log(item_id, access_time) VALUES (?, ?)";
    pub fn query_str(&self) -> &str {
        Self::QUERY
    }
}
impl InsertIntoAccessLog {
    pub fn execute(&self, client: &impl RusqliteClient) -> rusqlite::Result<usize> {
        self.prepare(client)?.execute(self.as_params())
    }
    pub fn prepare<'conn>(
        &self,
        client: &'conn impl RusqliteClient,
    ) -> rusqlite::Result<rusqlite::Statement<'conn>> {
        client.prepare(self.query_str())
    }
    pub fn as_params(&self) -> impl rusqlite::Params {
        (self.item_id, self.access_time)
    }
}
impl InsertIntoAccessLog {
    pub const fn builder() -> InsertIntoAccessLogBuilder<'static, ((), ())> {
        InsertIntoAccessLogBuilder {
            fields: ((), ()),
            _phantom: std::marker::PhantomData,
        }
    }
}
pub struct InsertIntoAccessLogBuilder<'a, Fields = ((), ())> {
    fields: Fields,
    _phantom: std::marker::PhantomData<&'a ()>,
}
impl<'a, AccessTime> InsertIntoAccessLogBuilder<'a, ((), AccessTime)> {
    pub fn item_id(self, item_id: i64) -> InsertIntoAccessLogBuilder<'a, (i64, AccessTime)> {
        let ((), access_time) = self.fields;
        let _phantom = self._phantom;
        InsertIntoAccessLogBuilder {
            fields: (item_id, access_time),
            _phantom,
        }
    }
}
impl<'a, ItemId> InsertIntoAccessLogBuilder<'a, (ItemId, ())> {
    pub fn access_time(self, access_time: i64) -> InsertIntoAccessLogBuilder<'a, (ItemId, i64)> {
        let (item_id, ()) = self.fields;
        let _phantom = self._phantom;
        InsertIntoAccessLogBuilder {
            fields: (item_id, access_time),
            _phantom,
        }
    }
}
impl<'a> InsertIntoAccessLogBuilder<'a, (i64, i64)> {
    pub fn build(self) -> InsertIntoAccessLog {
        let (item_id, access_time) = self.fields;
        InsertIntoAccessLog {
            item_id,
            access_time,
        }
    }
}
pub struct UpdateItemRow {
    pub id: i64,
}
impl UpdateItemRow {
    pub fn from_row(row: &rusqlite::Row) -> rusqlite::Result<Self> {
        Ok(Self { id: row.get(0)? })
    }
}
pub struct UpdateItem<'a> {
    new_key: Option<&'a str>,
    base_score: Option<i64>,
    update_time: i64,
    key: &'a str,
}
impl<'a> UpdateItem<'a> {
    pub const QUERY: &'static str = r"UPDATE item
SET
  item = COALESCE(?1, item),
  base_score = COALESCE(?2, base_score),
  update_time = ?3
WHERE item = ?4
RETURNING id";
    pub fn query_str(&self) -> &str {
        Self::QUERY
    }
}
impl<'a> UpdateItem<'a> {
    pub fn query_one(&self, client: &impl RusqliteClient) -> rusqlite::Result<UpdateItemRow> {
        self.prepare(client)?
            .query_row(self.as_params(), UpdateItemRow::from_row)
    }
    pub fn query_opt(
        &self,
        client: &impl RusqliteClient,
    ) -> rusqlite::Result<Option<UpdateItemRow>> {
        self.prepare(client)?
            .query_map(self.as_params(), UpdateItemRow::from_row)?
            .next()
            .transpose()
    }
    pub fn prepare<'conn>(
        &self,
        client: &'conn impl RusqliteClient,
    ) -> rusqlite::Result<rusqlite::Statement<'conn>> {
        client.prepare(self.query_str())
    }
    pub fn as_params(&self) -> impl rusqlite::Params {
        (self.new_key, self.base_score, self.update_time, self.key)
    }
}
impl<'a> UpdateItem<'a> {
    pub const fn builder() -> UpdateItemBuilder<'a, ((), (), (), ())> {
        UpdateItemBuilder {
            fields: ((), (), (), ()),
            _phantom: std::marker::PhantomData,
        }
    }
}
pub struct UpdateItemBuilder<'a, Fields = ((), (), (), ())> {
    fields: Fields,
    _phantom: std::marker::PhantomData<&'a ()>,
}
impl<'a, BaseScore, UpdateTime, Key> UpdateItemBuilder<'a, ((), BaseScore, UpdateTime, Key)> {
    pub fn new_key(
        self,
        new_key: Option<&'a str>,
    ) -> UpdateItemBuilder<'a, (Option<&'a str>, BaseScore, UpdateTime, Key)> {
        let ((), base_score, update_time, key) = self.fields;
        let _phantom = self._phantom;
        UpdateItemBuilder {
            fields: (new_key, base_score, update_time, key),
            _phantom,
        }
    }
}
impl<'a, NewKey, UpdateTime, Key> UpdateItemBuilder<'a, (NewKey, (), UpdateTime, Key)> {
    pub fn base_score(
        self,
        base_score: Option<i64>,
    ) -> UpdateItemBuilder<'a, (NewKey, Option<i64>, UpdateTime, Key)> {
        let (new_key, (), update_time, key) = self.fields;
        let _phantom = self._phantom;
        UpdateItemBuilder {
            fields: (new_key, base_score, update_time, key),
            _phantom,
        }
    }
}
impl<'a, NewKey, BaseScore, Key> UpdateItemBuilder<'a, (NewKey, BaseScore, (), Key)> {
    pub fn update_time(
        self,
        update_time: i64,
    ) -> UpdateItemBuilder<'a, (NewKey, BaseScore, i64, Key)> {
        let (new_key, base_score, (), key) = self.fields;
        let _phantom = self._phantom;
        UpdateItemBuilder {
            fields: (new_key, base_score, update_time, key),
            _phantom,
        }
    }
}
impl<'a, NewKey, BaseScore, UpdateTime> UpdateItemBuilder<'a, (NewKey, BaseScore, UpdateTime, ())> {
    pub fn key(
        self,
        key: &'a str,
    ) -> UpdateItemBuilder<'a, (NewKey, BaseScore, UpdateTime, &'a str)> {
        let (new_key, base_score, update_time, ()) = self.fields;
        let _phantom = self._phantom;
        UpdateItemBuilder {
            fields: (new_key, base_score, update_time, key),
            _phantom,
        }
    }
}
impl<'a> UpdateItemBuilder<'a, (Option<&'a str>, Option<i64>, i64, &'a str)> {
    pub fn build(self) -> UpdateItem<'a> {
        let (new_key, base_score, update_time, key) = self.fields;
        UpdateItem {
            new_key,
            base_score,
            update_time,
            key,
        }
    }
}
pub struct DeleteItemRow {
    pub id: i64,
}
impl DeleteItemRow {
    pub fn from_row(row: &rusqlite::Row) -> rusqlite::Result<Self> {
        Ok(Self { id: row.get(0)? })
    }
}
pub struct DeleteItem<'a> {
    key: &'a str,
}
impl<'a> DeleteItem<'a> {
    pub const QUERY: &'static str = r"DELETE FROM item
WHERE item = ?1
RETURNING id";
    pub fn query_str(&self) -> &str {
        Self::QUERY
    }
}
impl<'a> DeleteItem<'a> {
    pub fn query_one(&self, client: &impl RusqliteClient) -> rusqlite::Result<DeleteItemRow> {
        self.prepare(client)?
            .query_row(self.as_params(), DeleteItemRow::from_row)
    }
    pub fn query_opt(
        &self,
        client: &impl RusqliteClient,
    ) -> rusqlite::Result<Option<DeleteItemRow>> {
        self.prepare(client)?
            .query_map(self.as_params(), DeleteItemRow::from_row)?
            .next()
            .transpose()
    }
    pub fn prepare<'conn>(
        &self,
        client: &'conn impl RusqliteClient,
    ) -> rusqlite::Result<rusqlite::Statement<'conn>> {
        client.prepare(self.query_str())
    }
    pub fn as_params(&self) -> impl rusqlite::Params {
        (self.key,)
    }
}
impl<'a> DeleteItem<'a> {
    pub const fn builder() -> DeleteItemBuilder<'a, ((),)> {
        DeleteItemBuilder {
            fields: ((),),
            _phantom: std::marker::PhantomData,
        }
    }
}
pub struct DeleteItemBuilder<'a, Fields = ((),)> {
    fields: Fields,
    _phantom: std::marker::PhantomData<&'a ()>,
}
impl<'a> DeleteItemBuilder<'a, ((),)> {
    pub fn key(self, key: &'a str) -> DeleteItemBuilder<'a, (&'a str,)> {
        let ((),) = self.fields;
        let _phantom = self._phantom;
        DeleteItemBuilder {
            fields: (key,),
            _phantom,
        }
    }
}
impl<'a> DeleteItemBuilder<'a, (&'a str,)> {
    pub fn build(self) -> DeleteItem<'a> {
        let (key,) = self.fields;
        DeleteItem { key }
    }
}
pub struct SelectPruneCandidatesRow {
    pub id: i64,
    pub item: String,
    pub access_count: i64,
}
impl SelectPruneCandidatesRow {
    pub fn from_row(row: &rusqlite::Row) -> rusqlite::Result<Self> {
        Ok(Self {
            id: row.get(0)?,
            item: row.get(1)?,
            access_count: row.get(2)?,
        })
    }
}
pub struct SelectPruneCandidates<'a> {
    score_below: Option<f64>,
    prefix: Option<&'a str>,
    last_access_before: Option<i64>,
    created_before: Option<i64>,
    updated_before: Option<i64>,
    now: i64,
}
impl<'a> SelectPruneCandidates<'a> {
    pub const QUERY: &'static str = r"WITH candidates AS (
  SELECT
    i.id,
    i.item,
    CAST(COUNT(l.id) AS INTEGER) AS access_count,
    CAST(COALESCE(MAX(l.access_time), i.create_time) AS INTEGER) AS last_access_time,
    CAST(i.base_score
    + COALESCE(
      SUM(1.0 / (1.0 + MAX(?6 - l.access_time, 0) / 604800.0)),
      0
    ) AS REAL) AS frecency_score,
    i.create_time,
    i.update_time
  FROM item AS i
  LEFT JOIN access_log AS l ON l.item_id = i.id
  GROUP BY
    i.id,
    i.item,
    i.base_score,
    i.create_time,
    i.update_time
)
SELECT id, item, access_count
FROM candidates
WHERE (?1 IS NULL OR frecency_score < ?1)
  AND (
    CAST(?2 AS TEXT) IS NULL
    OR substr(item, 1, length(CAST(?2 AS TEXT))) = CAST(?2 AS TEXT)
  )
  AND (
    CAST(?3 AS INTEGER) IS NULL
    OR last_access_time <= CAST(?3 AS INTEGER)
  )
  AND (
    CAST(?4 AS INTEGER) IS NULL
    OR create_time < CAST(?4 AS INTEGER)
  )
  AND (
    CAST(?5 AS INTEGER) IS NULL
    OR update_time < CAST(?5 AS INTEGER)
  )
ORDER BY item";
    pub fn query_str(&self) -> &str {
        Self::QUERY
    }
}
impl<'a> SelectPruneCandidates<'a> {
    pub fn query_many(
        &self,
        client: &impl RusqliteClient,
    ) -> rusqlite::Result<Vec<SelectPruneCandidatesRow>> {
        self.prepare(client)?
            .query_map(self.as_params(), SelectPruneCandidatesRow::from_row)?
            .collect()
    }
    pub fn prepare<'conn>(
        &self,
        client: &'conn impl RusqliteClient,
    ) -> rusqlite::Result<rusqlite::Statement<'conn>> {
        client.prepare(self.query_str())
    }
    pub fn as_params(&self) -> impl rusqlite::Params {
        (
            self.score_below,
            self.prefix,
            self.last_access_before,
            self.created_before,
            self.updated_before,
            self.now,
        )
    }
}
impl<'a> SelectPruneCandidates<'a> {
    pub const fn builder() -> SelectPruneCandidatesBuilder<'a, ((), (), (), (), (), ())> {
        SelectPruneCandidatesBuilder {
            fields: ((), (), (), (), (), ()),
            _phantom: std::marker::PhantomData,
        }
    }
}
pub struct SelectPruneCandidatesBuilder<'a, Fields = ((), (), (), (), (), ())> {
    fields: Fields,
    _phantom: std::marker::PhantomData<&'a ()>,
}
impl<'a, Prefix, LastAccessBefore, CreatedBefore, UpdatedBefore, Now>
    SelectPruneCandidatesBuilder<
        'a,
        (
            (),
            Prefix,
            LastAccessBefore,
            CreatedBefore,
            UpdatedBefore,
            Now,
        ),
    >
{
    pub fn score_below(
        self,
        score_below: Option<f64>,
    ) -> SelectPruneCandidatesBuilder<
        'a,
        (
            Option<f64>,
            Prefix,
            LastAccessBefore,
            CreatedBefore,
            UpdatedBefore,
            Now,
        ),
    > {
        let ((), prefix, last_access_before, created_before, updated_before, now) = self.fields;
        let _phantom = self._phantom;
        SelectPruneCandidatesBuilder {
            fields: (
                score_below,
                prefix,
                last_access_before,
                created_before,
                updated_before,
                now,
            ),
            _phantom,
        }
    }
}
impl<'a, ScoreBelow, LastAccessBefore, CreatedBefore, UpdatedBefore, Now>
    SelectPruneCandidatesBuilder<
        'a,
        (
            ScoreBelow,
            (),
            LastAccessBefore,
            CreatedBefore,
            UpdatedBefore,
            Now,
        ),
    >
{
    pub fn prefix(
        self,
        prefix: Option<&'a str>,
    ) -> SelectPruneCandidatesBuilder<
        'a,
        (
            ScoreBelow,
            Option<&'a str>,
            LastAccessBefore,
            CreatedBefore,
            UpdatedBefore,
            Now,
        ),
    > {
        let (score_below, (), last_access_before, created_before, updated_before, now) =
            self.fields;
        let _phantom = self._phantom;
        SelectPruneCandidatesBuilder {
            fields: (
                score_below,
                prefix,
                last_access_before,
                created_before,
                updated_before,
                now,
            ),
            _phantom,
        }
    }
}
impl<'a, ScoreBelow, Prefix, CreatedBefore, UpdatedBefore, Now>
    SelectPruneCandidatesBuilder<'a, (ScoreBelow, Prefix, (), CreatedBefore, UpdatedBefore, Now)>
{
    pub fn last_access_before(
        self,
        last_access_before: Option<i64>,
    ) -> SelectPruneCandidatesBuilder<
        'a,
        (
            ScoreBelow,
            Prefix,
            Option<i64>,
            CreatedBefore,
            UpdatedBefore,
            Now,
        ),
    > {
        let (score_below, prefix, (), created_before, updated_before, now) = self.fields;
        let _phantom = self._phantom;
        SelectPruneCandidatesBuilder {
            fields: (
                score_below,
                prefix,
                last_access_before,
                created_before,
                updated_before,
                now,
            ),
            _phantom,
        }
    }
}
impl<'a, ScoreBelow, Prefix, LastAccessBefore, UpdatedBefore, Now>
    SelectPruneCandidatesBuilder<'a, (ScoreBelow, Prefix, LastAccessBefore, (), UpdatedBefore, Now)>
{
    pub fn created_before(
        self,
        created_before: Option<i64>,
    ) -> SelectPruneCandidatesBuilder<
        'a,
        (
            ScoreBelow,
            Prefix,
            LastAccessBefore,
            Option<i64>,
            UpdatedBefore,
            Now,
        ),
    > {
        let (score_below, prefix, last_access_before, (), updated_before, now) = self.fields;
        let _phantom = self._phantom;
        SelectPruneCandidatesBuilder {
            fields: (
                score_below,
                prefix,
                last_access_before,
                created_before,
                updated_before,
                now,
            ),
            _phantom,
        }
    }
}
impl<'a, ScoreBelow, Prefix, LastAccessBefore, CreatedBefore, Now>
    SelectPruneCandidatesBuilder<'a, (ScoreBelow, Prefix, LastAccessBefore, CreatedBefore, (), Now)>
{
    pub fn updated_before(
        self,
        updated_before: Option<i64>,
    ) -> SelectPruneCandidatesBuilder<
        'a,
        (
            ScoreBelow,
            Prefix,
            LastAccessBefore,
            CreatedBefore,
            Option<i64>,
            Now,
        ),
    > {
        let (score_below, prefix, last_access_before, created_before, (), now) = self.fields;
        let _phantom = self._phantom;
        SelectPruneCandidatesBuilder {
            fields: (
                score_below,
                prefix,
                last_access_before,
                created_before,
                updated_before,
                now,
            ),
            _phantom,
        }
    }
}
impl<'a, ScoreBelow, Prefix, LastAccessBefore, CreatedBefore, UpdatedBefore>
    SelectPruneCandidatesBuilder<
        'a,
        (
            ScoreBelow,
            Prefix,
            LastAccessBefore,
            CreatedBefore,
            UpdatedBefore,
            (),
        ),
    >
{
    pub fn now(
        self,
        now: i64,
    ) -> SelectPruneCandidatesBuilder<
        'a,
        (
            ScoreBelow,
            Prefix,
            LastAccessBefore,
            CreatedBefore,
            UpdatedBefore,
            i64,
        ),
    > {
        let (score_below, prefix, last_access_before, created_before, updated_before, ()) =
            self.fields;
        let _phantom = self._phantom;
        SelectPruneCandidatesBuilder {
            fields: (
                score_below,
                prefix,
                last_access_before,
                created_before,
                updated_before,
                now,
            ),
            _phantom,
        }
    }
}
impl<'a>
    SelectPruneCandidatesBuilder<
        'a,
        (
            Option<f64>,
            Option<&'a str>,
            Option<i64>,
            Option<i64>,
            Option<i64>,
            i64,
        ),
    >
{
    pub fn build(self) -> SelectPruneCandidates<'a> {
        let (score_below, prefix, last_access_before, created_before, updated_before, now) =
            self.fields;
        SelectPruneCandidates {
            score_below,
            prefix,
            last_access_before,
            created_before,
            updated_before,
            now,
        }
    }
}
pub struct DeleteItemByIdRow {}
impl DeleteItemByIdRow {
    pub fn from_row(row: &rusqlite::Row) -> rusqlite::Result<Self> {
        Ok(Self {})
    }
}
pub struct DeleteItemById {
    id: i64,
}
impl DeleteItemById {
    pub const QUERY: &'static str = r"DELETE FROM item WHERE id = ?1";
    pub fn query_str(&self) -> &str {
        Self::QUERY
    }
}
impl DeleteItemById {
    pub fn execute(&self, client: &impl RusqliteClient) -> rusqlite::Result<usize> {
        self.prepare(client)?.execute(self.as_params())
    }
    pub fn prepare<'conn>(
        &self,
        client: &'conn impl RusqliteClient,
    ) -> rusqlite::Result<rusqlite::Statement<'conn>> {
        client.prepare(self.query_str())
    }
    pub fn as_params(&self) -> impl rusqlite::Params {
        (self.id,)
    }
}
impl DeleteItemById {
    pub const fn builder() -> DeleteItemByIdBuilder<'static, ((),)> {
        DeleteItemByIdBuilder {
            fields: ((),),
            _phantom: std::marker::PhantomData,
        }
    }
}
pub struct DeleteItemByIdBuilder<'a, Fields = ((),)> {
    fields: Fields,
    _phantom: std::marker::PhantomData<&'a ()>,
}
impl<'a> DeleteItemByIdBuilder<'a, ((),)> {
    pub fn id(self, id: i64) -> DeleteItemByIdBuilder<'a, (i64,)> {
        let ((),) = self.fields;
        let _phantom = self._phantom;
        DeleteItemByIdBuilder {
            fields: (id,),
            _phantom,
        }
    }
}
impl<'a> DeleteItemByIdBuilder<'a, (i64,)> {
    pub fn build(self) -> DeleteItemById {
        let (id,) = self.fields;
        DeleteItemById { id }
    }
}
pub struct QuerySelectFromItemFrecencyRow {
    pub item: String,
    pub frecency_score: f64,
}
impl QuerySelectFromItemFrecencyRow {
    pub fn from_row(row: &rusqlite::Row) -> rusqlite::Result<Self> {
        Ok(Self {
            item: row.get(0)?,
            frecency_score: row.get(1)?,
        })
    }
}
pub struct QuerySelectFromItemFrecency<'a> {
    now: i64,
    prefix: Option<&'a str>,
    limit: i64,
}
impl<'a> QuerySelectFromItemFrecency<'a> {
    pub const QUERY: &'static str = r"SELECT
  i.item,
  CAST(i.base_score
  + COALESCE(
    SUM(1.0 / (1.0 + MAX(?1 - l.access_time, 0) / 604800.0)),
    0
  ) AS REAL) AS frecency_score
FROM item AS i
LEFT JOIN access_log AS l ON l.item_id = i.id
WHERE i.item LIKE ?2 || '%'
GROUP BY
  i.id,
  i.item,
  i.base_score
ORDER BY frecency_score DESC
LIMIT ?3";
    pub fn query_str(&self) -> &str {
        Self::QUERY
    }
}
impl<'a> QuerySelectFromItemFrecency<'a> {
    pub fn query_many(
        &self,
        client: &impl RusqliteClient,
    ) -> rusqlite::Result<Vec<QuerySelectFromItemFrecencyRow>> {
        self.prepare(client)?
            .query_map(self.as_params(), QuerySelectFromItemFrecencyRow::from_row)?
            .collect()
    }
    pub fn prepare<'conn>(
        &self,
        client: &'conn impl RusqliteClient,
    ) -> rusqlite::Result<rusqlite::Statement<'conn>> {
        client.prepare(self.query_str())
    }
    pub fn as_params(&self) -> impl rusqlite::Params {
        (self.now, self.prefix, self.limit)
    }
}
impl<'a> QuerySelectFromItemFrecency<'a> {
    pub const fn builder() -> QuerySelectFromItemFrecencyBuilder<'a, ((), (), ())> {
        QuerySelectFromItemFrecencyBuilder {
            fields: ((), (), ()),
            _phantom: std::marker::PhantomData,
        }
    }
}
pub struct QuerySelectFromItemFrecencyBuilder<'a, Fields = ((), (), ())> {
    fields: Fields,
    _phantom: std::marker::PhantomData<&'a ()>,
}
impl<'a, Prefix, Limit> QuerySelectFromItemFrecencyBuilder<'a, ((), Prefix, Limit)> {
    pub fn now(self, now: i64) -> QuerySelectFromItemFrecencyBuilder<'a, (i64, Prefix, Limit)> {
        let ((), prefix, limit) = self.fields;
        let _phantom = self._phantom;
        QuerySelectFromItemFrecencyBuilder {
            fields: (now, prefix, limit),
            _phantom,
        }
    }
}
impl<'a, Now, Limit> QuerySelectFromItemFrecencyBuilder<'a, (Now, (), Limit)> {
    pub fn prefix(
        self,
        prefix: Option<&'a str>,
    ) -> QuerySelectFromItemFrecencyBuilder<'a, (Now, Option<&'a str>, Limit)> {
        let (now, (), limit) = self.fields;
        let _phantom = self._phantom;
        QuerySelectFromItemFrecencyBuilder {
            fields: (now, prefix, limit),
            _phantom,
        }
    }
}
impl<'a, Now, Prefix> QuerySelectFromItemFrecencyBuilder<'a, (Now, Prefix, ())> {
    pub fn limit(self, limit: i64) -> QuerySelectFromItemFrecencyBuilder<'a, (Now, Prefix, i64)> {
        let (now, prefix, ()) = self.fields;
        let _phantom = self._phantom;
        QuerySelectFromItemFrecencyBuilder {
            fields: (now, prefix, limit),
            _phantom,
        }
    }
}
impl<'a> QuerySelectFromItemFrecencyBuilder<'a, (i64, Option<&'a str>, i64)> {
    pub fn build(self) -> QuerySelectFromItemFrecency<'a> {
        let (now, prefix, limit) = self.fields;
        QuerySelectFromItemFrecency { now, prefix, limit }
    }
}
