//! Code generated by sqlc-gen-rust. SHOULD NOT EDIT.
//! sqlc version: v1.31.1
//! sqlc-gen-rust version: v0.1.12

pub trait RusqliteClient {
    fn prepare(&self, sql: &str) -> rusqlite::Result<rusqlite::Statement<'_>>;
}
impl RusqliteClient for rusqlite::Connection {
    fn prepare(&self, sql: &str) -> rusqlite::Result<rusqlite::Statement<'_>> {
        self.prepare(sql)
    }
}
impl RusqliteClient for rusqlite::Transaction<'_> {
    fn prepare(&self, sql: &str) -> rusqlite::Result<rusqlite::Statement<'_>> {
        rusqlite::Connection::prepare(&self, sql)
    }
}
pub struct InsertOrUpdateItemRow {
    pub id: i64,
}
impl InsertOrUpdateItemRow {
    pub fn from_row(row: &rusqlite::Row) -> rusqlite::Result<Self> {
        Ok(Self { id: row.get(0)? })
    }
}
pub struct InsertOrUpdateItem<'a> {
    item: &'a str,
    base_score: i64,
    create_time: i64,
    update_time: i64,
}
impl<'a> InsertOrUpdateItem<'a> {
    pub const QUERY: &'static str = r"INSERT INTO item(item, base_score, create_time, update_time)
VALUES (?, ?, ?, ?)
ON CONFLICT (item) DO UPDATE
SET
  item = excluded.item
RETURNING id";
    pub fn query_str(&self) -> &str {
        Self::QUERY
    }
}
impl<'a> InsertOrUpdateItem<'a> {
    pub fn query_one(
        &self,
        client: &impl RusqliteClient,
    ) -> rusqlite::Result<InsertOrUpdateItemRow> {
        self.prepare(client)?
            .query_row(self.as_params(), InsertOrUpdateItemRow::from_row)
    }
    pub fn query_opt(
        &self,
        client: &impl RusqliteClient,
    ) -> rusqlite::Result<Option<InsertOrUpdateItemRow>> {
        self.prepare(client)?
            .query_map(self.as_params(), InsertOrUpdateItemRow::from_row)?
            .next()
            .transpose()
    }
    pub fn prepare<'conn>(
        &self,
        client: &'conn impl RusqliteClient,
    ) -> rusqlite::Result<rusqlite::Statement<'conn>> {
        client.prepare(self.query_str())
    }
    pub fn as_params(&self) -> impl rusqlite::Params {
        (
            self.item,
            self.base_score,
            self.create_time,
            self.update_time,
        )
    }
}
impl<'a> InsertOrUpdateItem<'a> {
    pub const fn builder() -> InsertOrUpdateItemBuilder<'a, ((), (), (), ())> {
        InsertOrUpdateItemBuilder {
            fields: ((), (), (), ()),
            _phantom: std::marker::PhantomData,
        }
    }
}
pub struct InsertOrUpdateItemBuilder<'a, Fields = ((), (), (), ())> {
    fields: Fields,
    _phantom: std::marker::PhantomData<&'a ()>,
}
impl<'a, BaseScore, CreateTime, UpdateTime>
    InsertOrUpdateItemBuilder<'a, ((), BaseScore, CreateTime, UpdateTime)>
{
    pub fn item(
        self,
        item: &'a str,
    ) -> InsertOrUpdateItemBuilder<'a, (&'a str, BaseScore, CreateTime, UpdateTime)> {
        let ((), base_score, create_time, update_time) = self.fields;
        let _phantom = self._phantom;
        InsertOrUpdateItemBuilder {
            fields: (item, base_score, create_time, update_time),
            _phantom,
        }
    }
}
impl<'a, Item, CreateTime, UpdateTime>
    InsertOrUpdateItemBuilder<'a, (Item, (), CreateTime, UpdateTime)>
{
    pub fn base_score(
        self,
        base_score: i64,
    ) -> InsertOrUpdateItemBuilder<'a, (Item, i64, CreateTime, UpdateTime)> {
        let (item, (), create_time, update_time) = self.fields;
        let _phantom = self._phantom;
        InsertOrUpdateItemBuilder {
            fields: (item, base_score, create_time, update_time),
            _phantom,
        }
    }
}
impl<'a, Item, BaseScore, UpdateTime>
    InsertOrUpdateItemBuilder<'a, (Item, BaseScore, (), UpdateTime)>
{
    pub fn create_time(
        self,
        create_time: i64,
    ) -> InsertOrUpdateItemBuilder<'a, (Item, BaseScore, i64, UpdateTime)> {
        let (item, base_score, (), update_time) = self.fields;
        let _phantom = self._phantom;
        InsertOrUpdateItemBuilder {
            fields: (item, base_score, create_time, update_time),
            _phantom,
        }
    }
}
impl<'a, Item, BaseScore, CreateTime>
    InsertOrUpdateItemBuilder<'a, (Item, BaseScore, CreateTime, ())>
{
    pub fn update_time(
        self,
        update_time: i64,
    ) -> InsertOrUpdateItemBuilder<'a, (Item, BaseScore, CreateTime, i64)> {
        let (item, base_score, create_time, ()) = self.fields;
        let _phantom = self._phantom;
        InsertOrUpdateItemBuilder {
            fields: (item, base_score, create_time, update_time),
            _phantom,
        }
    }
}
impl<'a> InsertOrUpdateItemBuilder<'a, (&'a str, i64, i64, i64)> {
    pub fn build(self) -> InsertOrUpdateItem<'a> {
        let (item, base_score, create_time, update_time) = self.fields;
        InsertOrUpdateItem {
            item,
            base_score,
            create_time,
            update_time,
        }
    }
}
pub struct InsertIntoAccessLogRow {}
impl InsertIntoAccessLogRow {
    pub fn from_row(row: &rusqlite::Row) -> rusqlite::Result<Self> {
        Ok(Self {})
    }
}
pub struct InsertIntoAccessLog {
    item_id: i64,
    access_time: i64,
}
impl InsertIntoAccessLog {
    pub const QUERY: &'static str = r"INSERT INTO access_log(item_id, access_time) VALUES (?, ?)";
    pub fn query_str(&self) -> &str {
        Self::QUERY
    }
}
impl InsertIntoAccessLog {
    pub fn execute(&self, client: &impl RusqliteClient) -> rusqlite::Result<usize> {
        self.prepare(client)?.execute(self.as_params())
    }
    pub fn prepare<'conn>(
        &self,
        client: &'conn impl RusqliteClient,
    ) -> rusqlite::Result<rusqlite::Statement<'conn>> {
        client.prepare(self.query_str())
    }
    pub fn as_params(&self) -> impl rusqlite::Params {
        (self.item_id, self.access_time)
    }
}
impl InsertIntoAccessLog {
    pub const fn builder() -> InsertIntoAccessLogBuilder<'static, ((), ())> {
        InsertIntoAccessLogBuilder {
            fields: ((), ()),
            _phantom: std::marker::PhantomData,
        }
    }
}
pub struct InsertIntoAccessLogBuilder<'a, Fields = ((), ())> {
    fields: Fields,
    _phantom: std::marker::PhantomData<&'a ()>,
}
impl<'a, AccessTime> InsertIntoAccessLogBuilder<'a, ((), AccessTime)> {
    pub fn item_id(self, item_id: i64) -> InsertIntoAccessLogBuilder<'a, (i64, AccessTime)> {
        let ((), access_time) = self.fields;
        let _phantom = self._phantom;
        InsertIntoAccessLogBuilder {
            fields: (item_id, access_time),
            _phantom,
        }
    }
}
impl<'a, ItemId> InsertIntoAccessLogBuilder<'a, (ItemId, ())> {
    pub fn access_time(self, access_time: i64) -> InsertIntoAccessLogBuilder<'a, (ItemId, i64)> {
        let (item_id, ()) = self.fields;
        let _phantom = self._phantom;
        InsertIntoAccessLogBuilder {
            fields: (item_id, access_time),
            _phantom,
        }
    }
}
impl<'a> InsertIntoAccessLogBuilder<'a, (i64, i64)> {
    pub fn build(self) -> InsertIntoAccessLog {
        let (item_id, access_time) = self.fields;
        InsertIntoAccessLog {
            item_id,
            access_time,
        }
    }
}
pub struct QuerySelectFromItemFrecencyRow {
    pub item: String,
    pub frecency_score: f64,
}
impl QuerySelectFromItemFrecencyRow {
    pub fn from_row(row: &rusqlite::Row) -> rusqlite::Result<Self> {
        Ok(Self {
            item: row.get(0)?,
            frecency_score: row.get(1)?,
        })
    }
}
pub struct QuerySelectFromItemFrecency<'a> {
    now: i64,
    prefix: Option<&'a str>,
    limit: i64,
}
impl<'a> QuerySelectFromItemFrecency<'a> {
    pub const QUERY: &'static str = r"SELECT
  i.item,
  CAST(i.base_score
  + COALESCE(
    SUM(1.0 / (1.0 + MAX(?1 - l.access_time, 0) / 604800.0)),
    0
  ) AS REAL) AS frecency_score
FROM item AS i
LEFT JOIN access_log AS l ON l.item_id = i.id
WHERE i.item LIKE ?2 || '%'
GROUP BY
  i.id,
  i.item,
  i.base_score
ORDER BY frecency_score DESC
LIMIT ?3";
    pub fn query_str(&self) -> &str {
        Self::QUERY
    }
}
impl<'a> QuerySelectFromItemFrecency<'a> {
    pub fn query_many(
        &self,
        client: &impl RusqliteClient,
    ) -> rusqlite::Result<Vec<QuerySelectFromItemFrecencyRow>> {
        self.prepare(client)?
            .query_map(self.as_params(), QuerySelectFromItemFrecencyRow::from_row)?
            .collect()
    }
    pub fn prepare<'conn>(
        &self,
        client: &'conn impl RusqliteClient,
    ) -> rusqlite::Result<rusqlite::Statement<'conn>> {
        client.prepare(self.query_str())
    }
    pub fn as_params(&self) -> impl rusqlite::Params {
        (self.now, self.prefix, self.limit)
    }
}
impl<'a> QuerySelectFromItemFrecency<'a> {
    pub const fn builder() -> QuerySelectFromItemFrecencyBuilder<'a, ((), (), ())> {
        QuerySelectFromItemFrecencyBuilder {
            fields: ((), (), ()),
            _phantom: std::marker::PhantomData,
        }
    }
}
pub struct QuerySelectFromItemFrecencyBuilder<'a, Fields = ((), (), ())> {
    fields: Fields,
    _phantom: std::marker::PhantomData<&'a ()>,
}
impl<'a, Prefix, Limit> QuerySelectFromItemFrecencyBuilder<'a, ((), Prefix, Limit)> {
    pub fn now(self, now: i64) -> QuerySelectFromItemFrecencyBuilder<'a, (i64, Prefix, Limit)> {
        let ((), prefix, limit) = self.fields;
        let _phantom = self._phantom;
        QuerySelectFromItemFrecencyBuilder {
            fields: (now, prefix, limit),
            _phantom,
        }
    }
}
impl<'a, Now, Limit> QuerySelectFromItemFrecencyBuilder<'a, (Now, (), Limit)> {
    pub fn prefix(
        self,
        prefix: Option<&'a str>,
    ) -> QuerySelectFromItemFrecencyBuilder<'a, (Now, Option<&'a str>, Limit)> {
        let (now, (), limit) = self.fields;
        let _phantom = self._phantom;
        QuerySelectFromItemFrecencyBuilder {
            fields: (now, prefix, limit),
            _phantom,
        }
    }
}
impl<'a, Now, Prefix> QuerySelectFromItemFrecencyBuilder<'a, (Now, Prefix, ())> {
    pub fn limit(self, limit: i64) -> QuerySelectFromItemFrecencyBuilder<'a, (Now, Prefix, i64)> {
        let (now, prefix, ()) = self.fields;
        let _phantom = self._phantom;
        QuerySelectFromItemFrecencyBuilder {
            fields: (now, prefix, limit),
            _phantom,
        }
    }
}
impl<'a> QuerySelectFromItemFrecencyBuilder<'a, (i64, Option<&'a str>, i64)> {
    pub fn build(self) -> QuerySelectFromItemFrecency<'a> {
        let (now, prefix, limit) = self.fields;
        QuerySelectFromItemFrecency { now, prefix, limit }
    }
}
