//! Code generated by sqlc-gen-rust. SHOULD NOT EDIT.
//! sqlc version: v1.31.1
//! sqlc-gen-rust version: v0.1.12

pub trait RusqliteClient {
    fn prepare(&self, sql: &str) -> rusqlite::Result<rusqlite::Statement<'_>>;
}
impl RusqliteClient for rusqlite::Connection {
    fn prepare(&self, sql: &str) -> rusqlite::Result<rusqlite::Statement<'_>> {
        self.prepare(sql)
    }
}
impl RusqliteClient for rusqlite::Transaction<'_> {
    fn prepare(&self, sql: &str) -> rusqlite::Result<rusqlite::Statement<'_>> {
        rusqlite::Connection::prepare(&self, sql)
    }
}
pub struct QueryItemsRow {
    pub id: i64,
    pub item: String,
    pub base_score: i64,
    pub create_datetime_rfc_3339: String,
    pub update_datetime_rfc_3339: String,
    pub access_count: i64,
    pub last_access_datetime_rfc_3339: Option<String>,
    pub frecency_score: f64,
}
impl QueryItemsRow {
    pub fn from_row(row: &rusqlite::Row) -> rusqlite::Result<Self> {
        Ok(Self {
            id: row.get(0)?,
            item: row.get(1)?,
            base_score: row.get(2)?,
            create_datetime_rfc_3339: row.get(3)?,
            update_datetime_rfc_3339: row.get(4)?,
            access_count: row.get(5)?,
            last_access_datetime_rfc_3339: row.get(6)?,
            frecency_score: row.get(7)?,
        })
    }
}
pub struct QueryItems<'a> {
    term: &'a str,
}
impl<'a> QueryItems<'a> {
    pub const QUERY: &'static str = r"SELECT id, item, base_score, create_datetime_rfc3339, update_datetime_rfc3339, access_count, last_access_datetime_rfc3339, frecency_score
FROM item_frecency
WHERE instr(item, ?1) > 0
ORDER BY frecency_score DESC";
    pub fn query_str(&self) -> &str {
        Self::QUERY
    }
}
impl<'a> QueryItems<'a> {
    pub fn query_many(&self, client: &impl RusqliteClient) -> rusqlite::Result<Vec<QueryItemsRow>> {
        self.prepare(client)?
            .query_map(self.as_params(), QueryItemsRow::from_row)?
            .collect()
    }
    pub fn prepare<'conn>(
        &self,
        client: &'conn impl RusqliteClient,
    ) -> rusqlite::Result<rusqlite::Statement<'conn>> {
        client.prepare(self.query_str())
    }
    pub fn as_params(&self) -> impl rusqlite::Params {
        (self.term,)
    }
}
impl<'a> QueryItems<'a> {
    pub const fn builder() -> QueryItemsBuilder<'a, ((),)> {
        QueryItemsBuilder {
            fields: ((),),
            _phantom: std::marker::PhantomData,
        }
    }
}
pub struct QueryItemsBuilder<'a, Fields = ((),)> {
    fields: Fields,
    _phantom: std::marker::PhantomData<&'a ()>,
}
impl<'a> QueryItemsBuilder<'a, ((),)> {
    pub fn term(self, term: &'a str) -> QueryItemsBuilder<'a, (&'a str,)> {
        let ((),) = self.fields;
        let _phantom = self._phantom;
        QueryItemsBuilder {
            fields: (term,),
            _phantom,
        }
    }
}
impl<'a> QueryItemsBuilder<'a, (&'a str,)> {
    pub fn build(self) -> QueryItems<'a> {
        let (term,) = self.fields;
        QueryItems { term }
    }
}
